# Adapted from the GitHub Python starter workflow:
# https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml

name: Trial problems

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12.0-beta.4"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Check types with mypy
        run: |
          python -m mypy .

      - name: Test a small problem
        run: |
          python main.py 0.3 5

      - name: Test a medium problem
        run: |
          python main.py 0.3 50

      - name: Test a large problem
        run: |
          python main.py 0.3 500
